global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "diabetes-monitor"

scrape_configs:
  - job_name: "fastapi-internal"
    scrape_interval: 5s
    metrics_path: /monitoring/prometheus/metrics
    static_configs:
      - targets: ['fastapi:8080']

  - job_name: "tf-serving-internal"
    scrape_interval: 5s
    metrics_path: /monitoring/prometheus/metrics
    static_configs:
      - targets: ['model-serving:8501']

  - job_name: "render-public"
    scheme: https
    scrape_interval: 15s
    metrics_path: /monitoring/prometheus/metrics
    static_configs:
      - targets: ['diabetes-detection-mlops.onrender.com']